AWSTemplateFormatVersion: '2010-09-09'
Description: HyperPod Cluster Only Stack

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label: 
          default: HyperPod Cluster Configuration
        Parameters: 
          - HyperPodClusterName
          - NodeRecovery
          - UseContinuousNodeProvisioningMode
      - Label: 
          default: Existing Infrastructure References
        Parameters: 
          - EKSClusterName
          - SageMakerIAMRoleName
          - PrivateSubnetId
          - SecurityGroupId
          - S3BucketName
      - Label: 
          default: Accelerated Instance Group
        Parameters: 
          - CreateAcceleratedInstanceGroup
          - AcceleratedInstanceGroupName
          - AcceleratedInstanceType
          - AcceleratedInstanceCount
          - AcceleratedEBSVolumeSize
          - AcceleratedThreadsPerCore
          - EnableInstanceStressCheck
          - EnableInstanceConnectivityCheck
          - AcceleratedLifeCycleConfigOnCreate
          - AcceleratedTrainingPlanArn
          - AcceleratedImageId
      - Label: 
          default: General Purpose Instance Group
        Parameters: 
          - CreateGeneralPurposeInstanceGroup
          - GeneralPurposeInstanceGroupName
          - GeneralPurposeInstanceType
          - GeneralPurposeInstanceCount
          - GeneralPurposeEBSVolumeSize
          - GeneralPurposeThreadsPerCore
          - GeneralPurposeLifeCycleConfigOnCreate
          - GeneralPurposeImageId
      - Label: 
          default: Restricted Instance Group
        Parameters:
          - CreateRestrictedInstanceGroup
          - RestrictedInstanceGroupName
          - RestrictedInstanceType
          - RestrictedInstanceCount
          - RestrictedPerUnitStorageThroughput
          - RestrictedSizeInGiB
          - RestrictedEBSVolumeSize
          - EnableRestrictedInstanceStressCheck
          - EnableRestrictedInstanceConnectivityCheck
          - RestrictedThreadsPerCore
          - RestrictedTrainingPlanArn

Mappings:
  AssetS3Buckets: 
    eu-north-1:
      BucketName: ws-assets-prod-iad-r-arn-580aeca3990cef5a
    ap-south-1:
      BucketName: ws-assets-prod-iad-r-bom-431207042d319a2d
    eu-west-3:
      BucketName: ws-assets-prod-iad-r-cdg-9e76383c31ad6229
    us-east-2:
      BucketName: ws-assets-prod-iad-r-cmh-8d6e9c21a4dec77d
    eu-west-1:
      BucketName: ws-assets-prod-iad-r-dub-85e3be25bd827406
    eu-central-1:
      BucketName: ws-assets-prod-iad-r-fra-b129423e91500967
    sa-east-1:
      BucketName: ws-assets-prod-iad-r-gru-527b8c19222c1182
    us-east-1:
      BucketName: ws-assets-prod-iad-r-iad-ed304a55c2ca1aee
    ap-northeast-2:
      BucketName: ws-assets-prod-iad-r-icn-ced060f0d38bc0b0
    ap-northeast-3:
      BucketName: ws-assets-prod-iad-r-kix-c2a28ad4e55ea53a
    eu-west-2:
      BucketName: ws-assets-prod-iad-r-lhr-cc4472a651221311
    ap-northeast-1:
      BucketName: ws-assets-prod-iad-r-nrt-2cb4b4649d0e0f94
    us-west-2:
      BucketName: ws-assets-prod-iad-r-pdx-f3b3f9f1a7d6a3d0
    us-west-1:
      BucketName: ws-assets-prod-iad-r-sfo-f61fc67057535f1b
    ap-southeast-1:
      BucketName: ws-assets-prod-iad-r-sin-694a125e41645312
    ap-southeast-2:
      BucketName: ws-assets-prod-iad-r-syd-b04c62a5f16f7b2e
    ca-central-1:
      BucketName: ws-assets-prod-iad-r-yul-5c2977cd61bca1f3

Parameters:
  ### ---------------- HyperPod Params ----------------###
  HyperPodClusterName:
    Description: Name of SageMaker HyperPod Cluster.
    Type: String
    Default: ml-cluster

  NodeRecovery:
    Description: Specifies whether to enable or disable the automatic node recovery feature (Automatic or None).
    Type: String
    Default: Automatic
    AllowedValues:
      - Automatic
      - None
  
  UseContinuousNodeProvisioningMode:
    Description: Whether to enable continuous node provisioning mode for the HyperPod cluster.
    Type: String
    Default: true
    AllowedValues: 
      - true
      - false

  ### ---------------- Existing Infrastructure ----------------###
  EKSClusterName:
    Description: The name of the existing EKS cluster.
    Type: String

  SageMakerIAMRoleName:
    Description: The name of the existing SageMaker IAM role.
    Type: String

  PrivateSubnetId:
    Description: The ID of the existing private subnet for HyperPod.
    Type: String

  SecurityGroupId:
    Description: The ID of the existing security group.
    Type: String

  S3BucketName:
    Description: The name of the existing S3 bucket for lifecycle scripts.
    Type: String

  ### ----------------  Accelerated Instance Group Params----------------###
  CreateAcceleratedInstanceGroup:
    Description: Whether to create an accelerated instance group for the HyperPod cluster.
    Type: String
    Default: true
    AllowedValues: 
      - true
      - false

  AcceleratedInstanceGroupName:
    Description: The name of the accelerated instance group for the HyperPod cluster.
    Type: String
    Default: accelerated-instance-group

  AcceleratedInstanceType:
    Description: The instance type of the accelerated instance group for the HyperPod cluster.
    Type: String
    Default: ml.g5.8xlarge

  AcceleratedInstanceCount:
    Description: The number of instances in the accelerated instance group for the HyperPod cluster.
    Type: Number
    Default: 1

  AcceleratedEBSVolumeSize:
    Description: > 
      The size in gigabytes (GB) of the additional EBS volume to be attached 
      to the instances in the accelerated instance group for the HyperPod cluster.
    Type: Number
    Default: 500

  AcceleratedThreadsPerCore:
    Description: The number of threads per CPU core in the accelerated instance group for the HyperPod cluster.
    Type: Number
    Default: 1
    AllowedValues:
      - 1
      - 2

  EnableInstanceStressCheck:
    Type: String
    Description: Enable instance stress deep health check
    Default: true
    AllowedValues: 
      - true
      - false

  EnableInstanceConnectivityCheck:
    Type: String
    Description: Enable instance connectivity deep health check
    Default: true
    AllowedValues: 
      - true
      - false

  AcceleratedLifeCycleConfigOnCreate:
    Description: The file name of lifecycle script for the accelerated instance group. This script runs during cluster creation.
    Type: String
    Default: on_create.sh

  AcceleratedTrainingPlanArn:
    Description: The ARN of the accelerated instance group training plan
    Type: String
    Default: ""

  AcceleratedImageId:
    Description: The AMI ID of the accelerated instance group for the HyperPod cluster.
    Type: String
    Default: ""

  ### ----------------  General Purpose Instance Group Params ----------------###
  CreateGeneralPurposeInstanceGroup: 
    Description: Whether to create a general purpose instance group for the HyperPod cluster.
    Type: String
    Default: false
    AllowedValues: 
      - true
      - false

  GeneralPurposeInstanceGroupName:
    Description: The name of the general purpose instance group for the HyperPod cluster.
    Type: String
    Default: general-purpose-instance-group

  GeneralPurposeInstanceType:
    Description: The instance type of the general purpose instance group for the HyperPod cluster.
    Type: String
    Default: ml.m5.2xlarge

  GeneralPurposeInstanceCount:
    Description: The number of instances in the general purpose instance group for the HyperPod cluster.
    Type: Number
    Default: 1

  GeneralPurposeEBSVolumeSize:
    Description: > 
      The size in gigabytes (GB) of the additional EBS volume to be attached 
      to the instances in the general purpose instance group for the HyperPod cluster.
    Type: Number
    Default: 500

  GeneralPurposeThreadsPerCore:
    Description: The number of threads per CPU core in the general purpose instance group for the HyperPod cluster.
    Type: Number
    Default: 1
    AllowedValues:
      - 1
      - 2

  GeneralPurposeLifeCycleConfigOnCreate:
    Description: The file name of lifecycle script for the general purpose instance group. This script runs during cluster creation.
    Type: String
    Default: on_create.sh
  
  GeneralPurposeImageId:
    Description: The AMI ID of the general purpose instance group for the HyperPod cluster.
    Type: String
    Default: ""
  
  ### ----------------  Restricted Instance Group Params ----------------###
  CreateRestrictedInstanceGroup:
    Description: Whether to create a restricted instance group for the HyperPod cluster.
    Type: String
    Default: false
    AllowedValues: 
      - true
      - false

  RestrictedInstanceGroupName: 
    Description: The name of the restricted instance group for the HyperPod cluster.
    Type: String
    Default: restricted-instance-group

  RestrictedInstanceType:
    Description: The instance type of the restricted instance group for the HyperPod cluster.
    Type: String
    Default: ml.g5.8xlarge

  RestrictedInstanceCount:
    Description: The number of instances in the restricted instance group for the HyperPod cluster.
    Type: Number
    Default: 1

  RestrictedPerUnitStorageThroughput:
    Description: The throughput for the service-managed FSx for Lustre file system 
    Type: Number
    Default: 250

  RestrictedSizeInGiB: 
    Description: The volume size for the service-managed FSx for Lustre file system
    Type: Number
    Default: 1200

  RestrictedEBSVolumeSize:
    Description: > 
        The size in gigabytes (GB) of the additional EBS volume to be attached 
        to the instances in the restricted instance group for the HyperPod cluster.
    Type: Number
    Default: 500

  EnableRestrictedInstanceStressCheck:
    Type: String
    Description: Enable restricted instance stress deep health check
    Default: true
    AllowedValues: 
      - true
      - false

  EnableRestrictedInstanceConnectivityCheck:
    Type: String
    Description: Enable restricted instance connectivity deep health check
    Default: true
    AllowedValues: 
      - true
      - false

  RestrictedThreadsPerCore:
    Description: The number of threads per CPU core in the restricted instance group for the HyperPod cluster.
    Type: Number
    Default: 1
    AllowedValues: 
      - 1 
      - 2

  RestrictedTrainingPlanArn:
    Description: The ARN of the restricted instance group training plan
    Type: String
    Default: ""

Resources:
  HyperPodClusterStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:
        Fn::Sub:
        - "https://${BucketName}.s3.${AWS::Region}.amazonaws.com/2433d39e-ccfe-4c00-9d3d-9917b729258e/hyperpod-cluster-stack.yaml"
        - BucketName: 
            Fn::FindInMap: 
            - AssetS3Buckets
            - Ref: 'AWS::Region'
            - BucketName
      Parameters:
        HyperPodClusterName: !Ref HyperPodClusterName
        NodeRecovery: !Ref NodeRecovery
        UseContinuousNodeProvisioningMode: !Ref UseContinuousNodeProvisioningMode
        CreateAcceleratedInstanceGroup: !Ref CreateAcceleratedInstanceGroup
        AcceleratedInstanceGroupName: !Ref AcceleratedInstanceGroupName
        AcceleratedInstanceType: !Ref AcceleratedInstanceType
        AcceleratedInstanceCount: !Ref AcceleratedInstanceCount
        AcceleratedEBSVolumeSize: !Ref AcceleratedEBSVolumeSize
        AcceleratedThreadsPerCore: !Ref AcceleratedThreadsPerCore
        EnableInstanceStressCheck: !Ref EnableInstanceStressCheck
        EnableInstanceConnectivityCheck: !Ref EnableInstanceConnectivityCheck
        AcceleratedLifeCycleConfigOnCreate: !Ref AcceleratedLifeCycleConfigOnCreate
        AcceleratedTrainingPlanArn: !Ref AcceleratedTrainingPlanArn
        AcceleratedImageId: !Ref AcceleratedImageId
        CreateGeneralPurposeInstanceGroup: !Ref CreateGeneralPurposeInstanceGroup
        GeneralPurposeInstanceGroupName: !Ref GeneralPurposeInstanceGroupName
        GeneralPurposeInstanceType: !Ref GeneralPurposeInstanceType
        GeneralPurposeInstanceCount: !Ref GeneralPurposeInstanceCount
        GeneralPurposeEBSVolumeSize: !Ref GeneralPurposeEBSVolumeSize
        GeneralPurposeThreadsPerCore: !Ref GeneralPurposeThreadsPerCore
        GeneralPurposeLifeCycleConfigOnCreate: !Ref GeneralPurposeLifeCycleConfigOnCreate
        GeneralPurposeImageId: !Ref GeneralPurposeImageId
        CreateRestrictedInstanceGroup: !Ref CreateRestrictedInstanceGroup
        RestrictedInstanceGroupName: !Ref RestrictedInstanceGroupName
        RestrictedInstanceType: !Ref RestrictedInstanceType
        RestrictedInstanceCount: !Ref RestrictedInstanceCount
        RestrictedPerUnitStorageThroughput: !Ref RestrictedPerUnitStorageThroughput
        RestrictedSizeInGiB: !Ref RestrictedSizeInGiB
        RestrictedEBSVolumeSize: !Ref RestrictedEBSVolumeSize
        EnableRestrictedInstanceStressCheck: !Ref EnableRestrictedInstanceStressCheck
        EnableRestrictedInstanceConnectivityCheck: !Ref EnableRestrictedInstanceConnectivityCheck
        RestrictedThreadsPerCore: !Ref RestrictedThreadsPerCore
        RestrictedTrainingPlanArn: !Ref RestrictedTrainingPlanArn
        HelmChartStatus: "HelmChartNotRequired"
        SageMakerIAMRoleName: !Ref SageMakerIAMRoleName
        PrivateSubnetId: !Ref PrivateSubnetId
        SecurityGroupId: !Ref SecurityGroupId
        EKSClusterName: !Ref EKSClusterName
        S3BucketName: !Ref S3BucketName

Outputs:
  HyperPodClusterName:
    Description: Name of the created HyperPod cluster
    Value: !GetAtt HyperPodClusterStack.Outputs.HyperPodClusterName

  HyperPodClusterArn:
    Description: ARN of the created HyperPod cluster
    Value: !GetAtt HyperPodClusterStack.Outputs.HyperPodClusterArn
